def nucleotide_counter(s):
    A, C, G, T = 0, 0, 0, 0

    for c in s:
        if c == 'A':
            A += 1
        elif c == 'C':
            C += 1
        elif c == 'G':
            G += 1
        elif c == 'T':
            T += 1
            
    return A, C, G, T

#dna = "AGAGTTTCATCAGGATCACAAGTGAGGAGTTATCGTATCGGGACTGTGAACTACGCGCGAGACTGAGTAGCCAGGAAGCTTTGGGTCCGCCAAGTGTTGGACACACACCGTGTTTTCTTGAATATTTTTCTCCCCTCGCGTAAAATCCTGACATTATCTAGAGACGCCCCCCCCAAGTACCTCGACCCACTCTCAGATGAGATCTATAGCTTGGATGTATAAGTCCCACCTCTATATTGCGTGATTGTCAGTTTCGGCAGCGCTTTCACTTACCGTTTGCGACCATGTCATTAAGGTGATATCCTCCGAAACGAGATCGGATCAACATTGTGGGGCGCAGAACGCCCTAGTACGCGAAACTCAGTCTTCACATCTTAAACAAGGGAAATGCATGAGCACAAATCGGAACTGCGCCGTAACATTTCGGCTGGTTCTACCGGCTGATCACCGGTGGTCACCAGGAATAGAAGATAGCGCAAGAAGAACTCAGGTTGCCATCTTTAACACGAATCTAAGGAGAGCCGTTGCTCCCCTCTATAGGAGATACAGCCTCCGCCGTCTAAGTAGTCCTAGCCGTAGCGTTACCGTCGACCCCGCATCGACCGAAGGTCACGGATCAACGGGTTAATGCAGCCTCTAATTTCGACCGTCGGGGACGAGCACTTCGAGTTCCTCAACAATAAGCTAATAACCAATAAATACGGTGCCTCACTCCTGGTGAGACCCGGATGTCAGGAATGGGGCACGCGCAATGTAAGCGTCTCTTCGTTCATATATGAGTAAATGCAGTTAATCTCCGTGGATGTATG"

#a, c, g, t = nucleotide_counter(dna)
#print(a, " ", c, " ", g, " ", t)
